# Generated by Django 5.0.2 on 2024-02-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0011_alter_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reteta',
            name='text',
            field=models.TextField(default='nimic'),
        ),
        migrations.AddField(
            model_name='reteta',
            name='timp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
